{
  "database_name": "retryable-reads-tests",
  "collection_name": "coll",
  "data": [
    {
      "_id": 1,
      "x": 11
    },
    {
      "_id": 2,
      "x": 22
    },
    {
      "_id": 3,
      "x": 33
    }
  ],
  "minServerVersion": "4.1.6",
  "tests": [
    {
      "description": "Aggregate succeeds after InterruptedAtShutdown",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 11600
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after InterruptedDueToStepDown",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 11602
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMaster",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMasterNoSlaveOk",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 13435
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NotMasterOrSecondary",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 13436
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after PrimarySteppedDown",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 189
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after ShutdownInProgress",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 91
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after HostNotFound",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 7
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after HostUnreachable",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 6
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after NetworkTimeout",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 89
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate succeeds after SocketException",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 9001
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": [
          {
            "_id": 2,
            "x": 22
          },
          {
            "_id": 3,
            "x": 33
          }
        ]
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate fails after two NotMaster errors",
      "clientOptions": {
        "retryReads": true
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 2
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": {
          "error": true
        }
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        },
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    },
    {
      "description": "Aggregate fails after NotMaster when retryReads is false",
      "clientOptions": {
        "retryReads": false
      },
      "failPoint": {
        "configureFailPoint": "failCommand",
        "mode": {
          "times": 1
        },
        "data": {
          "failCommands": [
            "aggregate"
          ],
          "errorCode": 10107
        }
      },
      "operation": {
        "name": "aggregate",
        "object": "collection",
        "arguments": {
          "pipeline": [
            {
              "$match": {
                "_id": {
                  "$gt": 1
                }
              }
            },
            {
              "$sort": {
                "x": 1
              }
            }
          ]
        },
        "result": {
          "error": true
        }
      },
      "expectations": [
        {
          "command_started_event": {
            "command": {
              "aggregate": "coll",
              "pipeline": [
                {
                  "$match": {
                    "_id": {
                      "$gt": 1
                    }
                  }
                },
                {
                  "$sort": {
                    "x": 1
                  }
                }
              ]
            },
            "database_name": "retryable-reads-tests"
          }
        }
      ]
    }
  ]
}
