database_name: &database_name "retryable-reads-tests"
collection_name: &collection_name "coll"

data:
    - {_id: 1, x: 11}
    - {_id: 2, x: 22}
    - {_id: 3, x: 33}
    - {_id: 4, x: 44}
    - {_id: 5, x: 55}

minServerVersion: '4.1.6' # 4.2

tests:
    -
        description: "Find succeeds after InterruptedAtShutdown"
        clientOptions:
            retryReads: true
        failPoint: &failCommand_failPoint
            configureFailPoint: failCommand
            mode: { times: 1 }
            data: { failCommands: [find], errorCode: 11600 }
        operation: &retryable_operation
            name: "find"
            object: collection
            arguments:
                filter: {}
                sort: {_id: 1}
                limit: 4
                batchSize: 2
            result:
                - {_id: 1, x: 11}
                - {_id: 2, x: 22}
                - {_id: 3, x: 33}
                - {_id: 4, x: 44}
        expectations:
            - &retryable_command_started_event
                command_started_event:
                    command:
                        find: *collection_name
                        filter: {}
                        sort: {_id: 1}
                        limit: 4
                        batchSize: 2
                    database_name: *database_name
            - *retryable_command_started_event
    -
        description: "Find succeeds after InterruptedDueToStepDown"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 11602 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after NotMaster"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 10107 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after NotMasterNoSlaveOk"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 13435 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after NotMasterOrSecondary"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 13436 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after PrimarySteppedDown"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 189 }
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after ShutdownInProgress"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 91 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after HostNotFound"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 7 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after HostUnreachable"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 6 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after NetworkTimeout"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 89 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event    
    -
        description: "Find succeeds after SocketException"
        clientOptions:
            retryReads: true
        failPoint:
            <<: *failCommand_failPoint
            data: { failCommands: [find], errorCode: 9001 }            
        operation: *retryable_operation
        expectations:
             - *retryable_command_started_event
             - *retryable_command_started_event 
