data:
    - { _id: 1, x: 11 }

minServerVersion: '3.6'

# Each test expects a network error for first attempt of the write command. The
# second attempt should return without error.
tests:
    -
        description: "DeleteOne succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "deleteOne"
            arguments:
                filter: { _id: 1 }
        outcome:
            result:
                deletedCount: 1
            collection:
                data: []
    -
        description: "FindOneAndDelete succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "FindOneAndDelete"
            arguments:
                filter: { _id: 1 }
        outcome:
            result: { _id: 1, x: 11 }
            collection:
                data: []
    -
        description: "FindOneAndReplace succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "FindOneAndReplace"
            arguments:
                filter: { _id: 1 }
                replacement: { _id: 1, x: 111 }
                returnDocument: Before
        outcome:
            result: { _id: 1, x: 11 }
            collection:
                data:
                    - { _id: 1, x: 111 }
    -
        description: "FindOneAndUpdate succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "FindOneAndUpdate"
            arguments:
                filter: { _id: 1 }
                update: { $inc: { x : 1 }}
        outcome:
            result: { _id: 1, x: 11 }
            collection:
                data:
                    - { _id: 1, x: 12 }
    -
        description: "InsertOne succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "insertOne"
            arguments:
                document: { _id: 2, x: 22 }
        outcome:
            result:
                insertedId: 2
            collection:
                data:
                    - { _id: 1, x: 11 }
                    - { _id: 2, x: 22 }
    -
        description: "ReplaceOne succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "replaceOne"
            arguments:
                filter: { _id: 1 }
                replacement: { _id: 1, x: 111 }
        outcome:
            result:
                matchedCount: 1
                modifiedCount: 1
                upsertedCount: 0
            collection:
                data:
                    - { _id: 1, x: 111 }
    -
        description: "UpdateOne succeeds after one network error"
        failPoint:
            times: 1
        operation:
            name: "updateOne"
            arguments:
                filter: { _id: 1 }
                update: { $inc: { x : 1 }}
        outcome:
            result:
                matchedCount: 1
                modifiedCount: 1
                upsertedCount: 0
            collection:
                data:
                    - { _id: 1, x: 12 }
    -
        description: "UpdateOne succeeds with upsert after one network error"
        failPoint:
            times: 1
        operation:
            name: "updateOne"
            arguments:
                filter: { _id: 2, x: 22 }
                update: { $inc: { x : 1 }}
                upsert: true
        outcome:
            result:
                matchedCount: 0
                modifiedCount: 0
                upsertedCount: 1
                upsertedId: 2
            collection:
                data:
                    - { _id: 1, x: 11 }
                    - { _id: 1, x: 23 }
